stages:
  - test
  - deploy

health_check:
  image: brianegan/dart-lcov:release-1.24.2
  stage: test
  script:
    - pub get
    - dartfmt -n .
    - dartanalyzer --fatal-warnings lib

unit_test:
  image: brianegan/dart-lcov:release-1.24.2
  stage: test
  script:
    - pub get && pub run test/reselect_test.dart

coverage:
  image: brianegan/dart-lcov:release-1.24.2
  stage: test
  script:
    - export PATH="$PATH":"~/.pub-cache/bin"
    - pub get --packages-dir
    - pub global activate coverage
    - pub global run coverage:collect_coverage --port=8111 -o coverage.json --resume-isolates --wait-paused &
    - dart --observe=8111 test/reselect_test.dart
    - pub global run coverage:format_coverage --package-root=packages --report-on lib --in coverage.json --out lcov.info --lcov
    - genhtml lcov.info --output=coverage
  artifacts:
    paths:
      - coverage/

pages:
  image: alpine
  stage: deploy
  dependencies:
    - coverage
  script:
    - mkdir public
    - mv coverage/ public/coverage/
  artifacts:
    paths:
      - public
  only:
    - master
