name: reselect
description: Efficiently derive data from your Redux Store
version: 0.1.0
homepage: https://gitlab.com/brianegan/reselect
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  func: ">=1.0.0 <2.0.0"
#  memoize:
#    path: "../memoize_dart"

dev_dependencies:
  test: ^0.12.0
