name: reselect
description: Efficiently derive data from your Redux Store
version: 0.5.0
homepage: https://github.com/brianegan/reselect_dart
author: Brian Egan <brian@brianegan.com>
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  memoize:
    git:
      url: https://github.com/ipcjs/memoize_dart.git
      ref: master
      

dev_dependencies:
  test: ^1.3.0
